import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/context/theme-context";

export const metadata: Metadata = {
  title: "bxzella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body>
            <Providers>{children}</Providers>
            <Toaster position="top-center" richColors />
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
