/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTradesRouteImport } from './routes/dashboard/trades'
import { Route as DashboardExchangeAccountsRouteImport } from './routes/dashboard/exchange-accounts'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as ApiTradesIndexRouteImport } from './routes/api/trades/index'
import { Route as ApiTradesSyncRouteImport } from './routes/api/trades/sync'
import { Route as ApiDashboardRecentTradesRouteImport } from './routes/api/dashboard/recent-trades'
import { Route as ApiDashboardOpenPositionsRouteImport } from './routes/api/dashboard/open-positions'
import { Route as ApiDashboardDailyPnlRouteImport } from './routes/api/dashboard/daily-pnl'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTradesRoute = DashboardTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExchangeAccountsRoute =
  DashboardExchangeAccountsRouteImport.update({
    id: '/exchange-accounts',
    path: '/exchange-accounts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesIndexRoute = ApiTradesIndexRouteImport.update({
  id: '/api/trades/',
  path: '/api/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesSyncRoute = ApiTradesSyncRouteImport.update({
  id: '/api/trades/sync',
  path: '/api/trades/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRecentTradesRoute =
  ApiDashboardRecentTradesRouteImport.update({
    id: '/recent-trades',
    path: '/recent-trades',
    getParentRoute: () => ApiDashboardRoute,
  } as any)
const ApiDashboardOpenPositionsRoute =
  ApiDashboardOpenPositionsRouteImport.update({
    id: '/open-positions',
    path: '/open-positions',
    getParentRoute: () => ApiDashboardRoute,
  } as any)
const ApiDashboardDailyPnlRoute = ApiDashboardDailyPnlRouteImport.update({
  id: '/daily-pnl',
  path: '/daily-pnl',
  getParentRoute: () => ApiDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/api/trades/': typeof ApiTradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/api/trades': typeof ApiTradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/api/trades/': typeof ApiTradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/dashboard'
    | '/dashboard/exchange-accounts'
    | '/dashboard/trades'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/trades/sync'
    | '/api/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/dashboard'
    | '/dashboard/exchange-accounts'
    | '/dashboard/trades'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/trades/sync'
    | '/api/trades'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/dashboard'
    | '/dashboard/exchange-accounts'
    | '/dashboard/trades'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/trades/sync'
    | '/api/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiDashboardRoute: typeof ApiDashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTradesSyncRoute: typeof ApiTradesSyncRoute
  ApiTradesIndexRoute: typeof ApiTradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/trades': {
      id: '/dashboard/trades'
      path: '/trades'
      fullPath: '/dashboard/trades'
      preLoaderRoute: typeof DashboardTradesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/exchange-accounts': {
      id: '/dashboard/exchange-accounts'
      path: '/exchange-accounts'
      fullPath: '/dashboard/exchange-accounts'
      preLoaderRoute: typeof DashboardExchangeAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/': {
      id: '/api/trades/'
      path: '/api/trades'
      fullPath: '/api/trades/'
      preLoaderRoute: typeof ApiTradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/sync': {
      id: '/api/trades/sync'
      path: '/api/trades/sync'
      fullPath: '/api/trades/sync'
      preLoaderRoute: typeof ApiTradesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/recent-trades': {
      id: '/api/dashboard/recent-trades'
      path: '/recent-trades'
      fullPath: '/api/dashboard/recent-trades'
      preLoaderRoute: typeof ApiDashboardRecentTradesRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/dashboard/open-positions': {
      id: '/api/dashboard/open-positions'
      path: '/open-positions'
      fullPath: '/api/dashboard/open-positions'
      preLoaderRoute: typeof ApiDashboardOpenPositionsRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/dashboard/daily-pnl': {
      id: '/api/dashboard/daily-pnl'
      path: '/daily-pnl'
      fullPath: '/api/dashboard/daily-pnl'
      preLoaderRoute: typeof ApiDashboardDailyPnlRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardExchangeAccountsRoute: typeof DashboardExchangeAccountsRoute
  DashboardTradesRoute: typeof DashboardTradesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardExchangeAccountsRoute: DashboardExchangeAccountsRoute,
  DashboardTradesRoute: DashboardTradesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiDashboardRouteChildren {
  ApiDashboardDailyPnlRoute: typeof ApiDashboardDailyPnlRoute
  ApiDashboardOpenPositionsRoute: typeof ApiDashboardOpenPositionsRoute
  ApiDashboardRecentTradesRoute: typeof ApiDashboardRecentTradesRoute
}

const ApiDashboardRouteChildren: ApiDashboardRouteChildren = {
  ApiDashboardDailyPnlRoute: ApiDashboardDailyPnlRoute,
  ApiDashboardOpenPositionsRoute: ApiDashboardOpenPositionsRoute,
  ApiDashboardRecentTradesRoute: ApiDashboardRecentTradesRoute,
}

const ApiDashboardRouteWithChildren = ApiDashboardRoute._addFileChildren(
  ApiDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiDashboardRoute: ApiDashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTradesSyncRoute: ApiTradesSyncRoute,
  ApiTradesIndexRoute: ApiTradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
