/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardExchangeAccountsRouteImport } from './routes/dashboard/exchange-accounts'
import { Route as DashboardAiSummarySubscriptionsRouteImport } from './routes/dashboard/ai-summary-subscriptions'
import { Route as ApiKlineRouteImport } from './routes/api/kline'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiAiSummarySubscriptionsRouteImport } from './routes/api/ai-summary-subscriptions'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as DashboardTradesIndexRouteImport } from './routes/dashboard/trades/index'
import { Route as ApiTradesIndexRouteImport } from './routes/api/trades/index'
import { Route as ApiNotebookTemplatesIndexRouteImport } from './routes/api/notebook-templates/index'
import { Route as DashboardTradesPositionIdRouteImport } from './routes/dashboard/trades/$positionId'
import { Route as ApiTradesSyncRouteImport } from './routes/api/trades/sync'
import { Route as ApiTradesPositionIdRouteImport } from './routes/api/trades/$positionId'
import { Route as ApiJobsAiSummaryRouteImport } from './routes/api/jobs/ai-summary'
import { Route as ApiDashboardRecentTradesRouteImport } from './routes/api/dashboard/recent-trades'
import { Route as ApiDashboardOpenPositionsRouteImport } from './routes/api/dashboard/open-positions'
import { Route as ApiDashboardDailyPnlRouteImport } from './routes/api/dashboard/daily-pnl'
import { Route as ApiCronWeeklySummaryRouteImport } from './routes/api/cron/weekly-summary'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiNotebooksTradeTradeIdRouteImport } from './routes/api/notebooks/trade/$tradeId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExchangeAccountsRoute =
  DashboardExchangeAccountsRouteImport.update({
    id: '/exchange-accounts',
    path: '/exchange-accounts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAiSummarySubscriptionsRoute =
  DashboardAiSummarySubscriptionsRouteImport.update({
    id: '/ai-summary-subscriptions',
    path: '/ai-summary-subscriptions',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiKlineRoute = ApiKlineRouteImport.update({
  id: '/api/kline',
  path: '/api/kline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummarySubscriptionsRoute =
  ApiAiSummarySubscriptionsRouteImport.update({
    id: '/api/ai-summary-subscriptions',
    path: '/api/ai-summary-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTradesIndexRoute = DashboardTradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTradesIndexRoute = ApiTradesIndexRouteImport.update({
  id: '/api/trades/',
  path: '/api/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebookTemplatesIndexRoute =
  ApiNotebookTemplatesIndexRouteImport.update({
    id: '/api/notebook-templates/',
    path: '/api/notebook-templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTradesPositionIdRoute =
  DashboardTradesPositionIdRouteImport.update({
    id: '/trades/$positionId',
    path: '/trades/$positionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiTradesSyncRoute = ApiTradesSyncRouteImport.update({
  id: '/api/trades/sync',
  path: '/api/trades/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesPositionIdRoute = ApiTradesPositionIdRouteImport.update({
  id: '/api/trades/$positionId',
  path: '/api/trades/$positionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsAiSummaryRoute = ApiJobsAiSummaryRouteImport.update({
  id: '/api/jobs/ai-summary',
  path: '/api/jobs/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRecentTradesRoute =
  ApiDashboardRecentTradesRouteImport.update({
    id: '/recent-trades',
    path: '/recent-trades',
    getParentRoute: () => ApiDashboardRoute,
  } as any)
const ApiDashboardOpenPositionsRoute =
  ApiDashboardOpenPositionsRouteImport.update({
    id: '/open-positions',
    path: '/open-positions',
    getParentRoute: () => ApiDashboardRoute,
  } as any)
const ApiDashboardDailyPnlRoute = ApiDashboardDailyPnlRouteImport.update({
  id: '/daily-pnl',
  path: '/daily-pnl',
  getParentRoute: () => ApiDashboardRoute,
} as any)
const ApiCronWeeklySummaryRoute = ApiCronWeeklySummaryRouteImport.update({
  id: '/api/cron/weekly-summary',
  path: '/api/cron/weekly-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebooksTradeTradeIdRoute =
  ApiNotebooksTradeTradeIdRouteImport.update({
    id: '/api/notebooks/trade/$tradeId',
    path: '/api/notebooks/trade/$tradeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/ai-summary-subscriptions': typeof ApiAiSummarySubscriptionsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/kline': typeof ApiKlineRoute
  '/dashboard/ai-summary-subscriptions': typeof DashboardAiSummarySubscriptionsRoute
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-summary': typeof ApiCronWeeklySummaryRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/jobs/ai-summary': typeof ApiJobsAiSummaryRoute
  '/api/trades/$positionId': typeof ApiTradesPositionIdRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/dashboard/trades/$positionId': typeof DashboardTradesPositionIdRoute
  '/api/notebook-templates/': typeof ApiNotebookTemplatesIndexRoute
  '/api/trades/': typeof ApiTradesIndexRoute
  '/dashboard/trades/': typeof DashboardTradesIndexRoute
  '/api/notebooks/trade/$tradeId': typeof ApiNotebooksTradeTradeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/ai-summary-subscriptions': typeof ApiAiSummarySubscriptionsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/kline': typeof ApiKlineRoute
  '/dashboard/ai-summary-subscriptions': typeof DashboardAiSummarySubscriptionsRoute
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-summary': typeof ApiCronWeeklySummaryRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/jobs/ai-summary': typeof ApiJobsAiSummaryRoute
  '/api/trades/$positionId': typeof ApiTradesPositionIdRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/dashboard/trades/$positionId': typeof DashboardTradesPositionIdRoute
  '/api/notebook-templates': typeof ApiNotebookTemplatesIndexRoute
  '/api/trades': typeof ApiTradesIndexRoute
  '/dashboard/trades': typeof DashboardTradesIndexRoute
  '/api/notebooks/trade/$tradeId': typeof ApiNotebooksTradeTradeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/ai-summary-subscriptions': typeof ApiAiSummarySubscriptionsRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/kline': typeof ApiKlineRoute
  '/dashboard/ai-summary-subscriptions': typeof DashboardAiSummarySubscriptionsRoute
  '/dashboard/exchange-accounts': typeof DashboardExchangeAccountsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-summary': typeof ApiCronWeeklySummaryRoute
  '/api/dashboard/daily-pnl': typeof ApiDashboardDailyPnlRoute
  '/api/dashboard/open-positions': typeof ApiDashboardOpenPositionsRoute
  '/api/dashboard/recent-trades': typeof ApiDashboardRecentTradesRoute
  '/api/jobs/ai-summary': typeof ApiJobsAiSummaryRoute
  '/api/trades/$positionId': typeof ApiTradesPositionIdRoute
  '/api/trades/sync': typeof ApiTradesSyncRoute
  '/dashboard/trades/$positionId': typeof DashboardTradesPositionIdRoute
  '/api/notebook-templates/': typeof ApiNotebookTemplatesIndexRoute
  '/api/trades/': typeof ApiTradesIndexRoute
  '/dashboard/trades/': typeof DashboardTradesIndexRoute
  '/api/notebooks/trade/$tradeId': typeof ApiNotebooksTradeTradeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/ai-summary-subscriptions'
    | '/api/dashboard'
    | '/api/kline'
    | '/dashboard/ai-summary-subscriptions'
    | '/dashboard/exchange-accounts'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/weekly-summary'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/jobs/ai-summary'
    | '/api/trades/$positionId'
    | '/api/trades/sync'
    | '/dashboard/trades/$positionId'
    | '/api/notebook-templates/'
    | '/api/trades/'
    | '/dashboard/trades/'
    | '/api/notebooks/trade/$tradeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/ai-summary-subscriptions'
    | '/api/dashboard'
    | '/api/kline'
    | '/dashboard/ai-summary-subscriptions'
    | '/dashboard/exchange-accounts'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/cron/weekly-summary'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/jobs/ai-summary'
    | '/api/trades/$positionId'
    | '/api/trades/sync'
    | '/dashboard/trades/$positionId'
    | '/api/notebook-templates'
    | '/api/trades'
    | '/dashboard/trades'
    | '/api/notebooks/trade/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/api/accounts'
    | '/api/ai-summary-subscriptions'
    | '/api/dashboard'
    | '/api/kline'
    | '/dashboard/ai-summary-subscriptions'
    | '/dashboard/exchange-accounts'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/weekly-summary'
    | '/api/dashboard/daily-pnl'
    | '/api/dashboard/open-positions'
    | '/api/dashboard/recent-trades'
    | '/api/jobs/ai-summary'
    | '/api/trades/$positionId'
    | '/api/trades/sync'
    | '/dashboard/trades/$positionId'
    | '/api/notebook-templates/'
    | '/api/trades/'
    | '/dashboard/trades/'
    | '/api/notebooks/trade/$tradeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiAiSummarySubscriptionsRoute: typeof ApiAiSummarySubscriptionsRoute
  ApiDashboardRoute: typeof ApiDashboardRouteWithChildren
  ApiKlineRoute: typeof ApiKlineRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronWeeklySummaryRoute: typeof ApiCronWeeklySummaryRoute
  ApiJobsAiSummaryRoute: typeof ApiJobsAiSummaryRoute
  ApiTradesPositionIdRoute: typeof ApiTradesPositionIdRoute
  ApiTradesSyncRoute: typeof ApiTradesSyncRoute
  ApiNotebookTemplatesIndexRoute: typeof ApiNotebookTemplatesIndexRoute
  ApiTradesIndexRoute: typeof ApiTradesIndexRoute
  ApiNotebooksTradeTradeIdRoute: typeof ApiNotebooksTradeTradeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/exchange-accounts': {
      id: '/dashboard/exchange-accounts'
      path: '/exchange-accounts'
      fullPath: '/dashboard/exchange-accounts'
      preLoaderRoute: typeof DashboardExchangeAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-summary-subscriptions': {
      id: '/dashboard/ai-summary-subscriptions'
      path: '/ai-summary-subscriptions'
      fullPath: '/dashboard/ai-summary-subscriptions'
      preLoaderRoute: typeof DashboardAiSummarySubscriptionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/kline': {
      id: '/api/kline'
      path: '/api/kline'
      fullPath: '/api/kline'
      preLoaderRoute: typeof ApiKlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-summary-subscriptions': {
      id: '/api/ai-summary-subscriptions'
      path: '/api/ai-summary-subscriptions'
      fullPath: '/api/ai-summary-subscriptions'
      preLoaderRoute: typeof ApiAiSummarySubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trades/': {
      id: '/dashboard/trades/'
      path: '/trades'
      fullPath: '/dashboard/trades/'
      preLoaderRoute: typeof DashboardTradesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trades/': {
      id: '/api/trades/'
      path: '/api/trades'
      fullPath: '/api/trades/'
      preLoaderRoute: typeof ApiTradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebook-templates/': {
      id: '/api/notebook-templates/'
      path: '/api/notebook-templates'
      fullPath: '/api/notebook-templates/'
      preLoaderRoute: typeof ApiNotebookTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trades/$positionId': {
      id: '/dashboard/trades/$positionId'
      path: '/trades/$positionId'
      fullPath: '/dashboard/trades/$positionId'
      preLoaderRoute: typeof DashboardTradesPositionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trades/sync': {
      id: '/api/trades/sync'
      path: '/api/trades/sync'
      fullPath: '/api/trades/sync'
      preLoaderRoute: typeof ApiTradesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades/$positionId': {
      id: '/api/trades/$positionId'
      path: '/api/trades/$positionId'
      fullPath: '/api/trades/$positionId'
      preLoaderRoute: typeof ApiTradesPositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/ai-summary': {
      id: '/api/jobs/ai-summary'
      path: '/api/jobs/ai-summary'
      fullPath: '/api/jobs/ai-summary'
      preLoaderRoute: typeof ApiJobsAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/recent-trades': {
      id: '/api/dashboard/recent-trades'
      path: '/recent-trades'
      fullPath: '/api/dashboard/recent-trades'
      preLoaderRoute: typeof ApiDashboardRecentTradesRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/dashboard/open-positions': {
      id: '/api/dashboard/open-positions'
      path: '/open-positions'
      fullPath: '/api/dashboard/open-positions'
      preLoaderRoute: typeof ApiDashboardOpenPositionsRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/dashboard/daily-pnl': {
      id: '/api/dashboard/daily-pnl'
      path: '/daily-pnl'
      fullPath: '/api/dashboard/daily-pnl'
      preLoaderRoute: typeof ApiDashboardDailyPnlRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/cron/weekly-summary': {
      id: '/api/cron/weekly-summary'
      path: '/api/cron/weekly-summary'
      fullPath: '/api/cron/weekly-summary'
      preLoaderRoute: typeof ApiCronWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebooks/trade/$tradeId': {
      id: '/api/notebooks/trade/$tradeId'
      path: '/api/notebooks/trade/$tradeId'
      fullPath: '/api/notebooks/trade/$tradeId'
      preLoaderRoute: typeof ApiNotebooksTradeTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAiSummarySubscriptionsRoute: typeof DashboardAiSummarySubscriptionsRoute
  DashboardExchangeAccountsRoute: typeof DashboardExchangeAccountsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTradesPositionIdRoute: typeof DashboardTradesPositionIdRoute
  DashboardTradesIndexRoute: typeof DashboardTradesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiSummarySubscriptionsRoute: DashboardAiSummarySubscriptionsRoute,
  DashboardExchangeAccountsRoute: DashboardExchangeAccountsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTradesPositionIdRoute: DashboardTradesPositionIdRoute,
  DashboardTradesIndexRoute: DashboardTradesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiDashboardRouteChildren {
  ApiDashboardDailyPnlRoute: typeof ApiDashboardDailyPnlRoute
  ApiDashboardOpenPositionsRoute: typeof ApiDashboardOpenPositionsRoute
  ApiDashboardRecentTradesRoute: typeof ApiDashboardRecentTradesRoute
}

const ApiDashboardRouteChildren: ApiDashboardRouteChildren = {
  ApiDashboardDailyPnlRoute: ApiDashboardDailyPnlRoute,
  ApiDashboardOpenPositionsRoute: ApiDashboardOpenPositionsRoute,
  ApiDashboardRecentTradesRoute: ApiDashboardRecentTradesRoute,
}

const ApiDashboardRouteWithChildren = ApiDashboardRoute._addFileChildren(
  ApiDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiAiSummarySubscriptionsRoute: ApiAiSummarySubscriptionsRoute,
  ApiDashboardRoute: ApiDashboardRouteWithChildren,
  ApiKlineRoute: ApiKlineRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronWeeklySummaryRoute: ApiCronWeeklySummaryRoute,
  ApiJobsAiSummaryRoute: ApiJobsAiSummaryRoute,
  ApiTradesPositionIdRoute: ApiTradesPositionIdRoute,
  ApiTradesSyncRoute: ApiTradesSyncRoute,
  ApiNotebookTemplatesIndexRoute: ApiNotebookTemplatesIndexRoute,
  ApiTradesIndexRoute: ApiTradesIndexRoute,
  ApiNotebooksTradeTradeIdRoute: ApiNotebooksTradeTradeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
